name: miscellanea
author: Eric McCormick
description: >
  A micro-site for miscellaneous throughts, musings, and other things that don't quite fit in my blog or AMA.
twitter_username: edm00se
github_username: edm00se
permalink: /misc/:title
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
