title: miscellanea
author: Eric McCormick
shortname: misc
twitter_username: edm00se
github_username: edm00se
google_analytics: UA-53507706-3
url: "https://edm00se.codes/"
baseurl: "misc"
permalink: :title
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# collections
# collections:
#   # development track
#   dev:
#     output: true
#     permalink: /:collection/:name
